# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/centos-7.4"
 # config.vm.network "public_network", ip: "192.168.1.10"
  config.vm.hostname = "elk"
  config.berkshelf.enabled = true

  config.vm.provision "chef_solo" do |chef|
 chef.json = {
      "java" => {
        "jdk_version" => "8"
      }
   }
       chef.add_recipe "ntp"
       chef.add_recipe "java"
       chef.add_recipe "elasticsearch"
       chef.add_recipe "logstash"
       chef.add_recipe "kibana5"
  end 

  config.vm.provision :serverspec do |spec|
   spec.pattern = 'spec/*_spec.rb'
   # save result into html an report, saved into a 'rspec_html_reports' directory. Default: false
    spec.html_output = true
  end
end
